Update main-pipeline.yml

diff --git a/.github/workflows/main-pipeline.yml b/.github/workflows/main-pipeline.yml
--- a/.github/workflows/main-pipeline.yml
+++ b/.github/workflows/main-pipeline.yml
@@ -29,32 +29,26 @@ jobs:
           output_file_path: results/checkov-results.json
         continue-on-error: true
 
-      - name: Run Gitleaks (Secret Scan)
-        uses: gitleaks/gitleaks-action@v2.3.7
-        with:
-          config: .gitleaks.toml
-          report-format: json
-          report-path: results/gitleaks-report.json
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        continue-on-error: true
+      - name: Verify Checkov Execution
+        run: |
+          if [ ! -s results/checkov-results.json ]; then
+            echo "❌ Error: El archivo checkov-results.json no existe o está vacío."
+            exit 1
+          else
+            echo "✅ Archivo encontrado, procediendo con la carga."
+          fi
+
+      - name: Verificar conexión con DefectDojo
+        run: |
+          curl -X GET "http://3.135.211.4:8080/api/v2/engagements/" \
+            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
+            -H "Accept: application/json"
 
       - name: Upload Checkov Report to DefectDojo
         uses: ivanamat/defectdojo-import-scan@v1
         with:
           token: ${{ secrets.DEFECTDOJO_API_KEY }}
-          defectdojo_url: "http://3.135.211.4:8080"
+          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
           file: results/checkov-results.json
           scan_type: Checkov Scan
           engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
-        continue-on-error: true
-
-      - name: Upload Gitleaks Report to DefectDojo
-        uses: ivanamat/defectdojo-import-scan@v1
-        with:
-          token: ${{ secrets.DEFECTDOJO_API_KEY }}
-          defectdojo_url: "http://3.135.211.4:8080"
-          file: results/gitleaks-report.json
-          scan_type: Gitleaks Scan
-          engagement: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
-        continue-on-error: true
